#pragma kernel Density
#include "Includes/Density.compute"

StructuredBuffer<float> rhob;

[numthreads(numThreads,numThreads,numThreads)]
void Density (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= numPointsPerAxis || id.y >= numPointsPerAxis || id.z >= numPointsPerAxis) {
        return;
    }

    float3 pos = centre + id * spacing - boundsSize/2;

    int index = indexFromCoord(id.x,id.y,id.z);
    int rhoindex = indexFromCoord_xtoy(id.x,id.y,id.z);
    points[index] = float4(pos, rhob[rhoindex]);
}